"""
Stage 0-R4 aggregation entry point. Reads ONLY from
data/per_sample_final_v4.csv (built by the v4 build_canonical.py, which adds
ONE fix on top of v3's Mondrian-split fix: Split CP's single pooled
calibration quantile q_hat is now the direct k-th order statistic instead of
an np.quantile approximation that silently shifted the selected index by one
-- the same fix, and the same off-by-one bug, as v3's Mondrian CP (split) fix
-- see build_canonical.py's module docstring. Only q_hat and
lo_sp/hi_sp/width_sp/covered_sp differ from v3; every other column, including
Mondrian CP and stage_cusum, is bit-identical, verified by diff). v1's, v2's,
and v3's tables and per_sample_final*.csv are kept, unmodified, under
tables/v1_superseded/, tables/v2_superseded/, tables/v3_superseded/, and
data/ respectively (see README's "superseded" note) -- this script never
reads or writes any of them.

table_h_sensitivity (k held fixed, h in {5,7,10}, 48 rows) was reintroduced
in v3 (previously only existed in the withdrawn v1 pipeline); it is now
regenerated against the v4 canonical file, picking up the Split CP fix too.

Changes vs v1 aggregate.py (carried over from v2/v3, still apply in v4):
  - table_main: Mondrian ECR reported as finite-only (the single number used
    for "which stage is worst"); unbounded rate is its own column, not mixed
    into the headline number. The two-convention (unbounded-as-covered vs
    finite-only) comparison is kept, but moved to its own table
    (table_mondrian_unbounded_v4) rather than cluttering the main table.
  - table_trainpct_cohort: train-set-percentile convention, restricted to the
    "cohort" of (seed,unit) instances that have at least one window in ALL
    THREE stages (many short-lived eval units never reach the train-set's
    absolute-cycle 'late' threshold at all under the full-availability table
    B_trainpct_final -- this table asks whether the worst-stage finding
    changes once that structural imbalance is controlled for). Reported
    side by side with the full-availability version. The same cohort
    restriction is applied to CUSUM as a confirmatory check (excluding
    instances where CUSUM never triggered) -- reported to confirm findings
    are unchanged, not because a different answer was expected.
  - paired_diff: primary CI is a unique-ENGINE block bootstrap (block = one
    raw C-MAPSS unit id's ENTIRE set of instances across all 5 seeds it
    appears as an eval unit in -- a block is drawn or not drawn as a whole,
    10,000 resamples). The old per-(seed,unit)-instance bootstrap is kept as
    a sensitivity column alongside it, not replaced.
  - table_matched: caption states explicitly that the fixed proportions are
    the EVALUATION set's mean CUSUM(h=7) stage occupancy; reports the max
    absolute |ECR_matched - ECR_cusum| across all (fd,method,stage) cells.
  - trainpct_thresholds_final_v4 (the "bucket geometry" table): gains an
    n_cohort_instances column (per fd,seed) alongside the existing
    p33/p67/frac_eval_shorter_than_train_median columns.
"""
import numpy as np
import pandas as pd
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent  # scripts/ -> repo root
DATA = REPO / 'data'
TABLES = REPO / 'tables'
TABLES.mkdir(parents=True, exist_ok=True)
FDS = ['FD001', 'FD002', 'FD003', 'FD004']
METHODS = [('mc', 'MC-Dropout'), ('sp', 'Split CP'),
           ('mo', 'Mondrian CP (online)'), ('mf', 'Mondrian CP (split)')]
CONVENTIONS = [('Fixed-fraction', 'stage_fixed'), ('CUSUM', 'stage_cusum'),
               ('TrainPct', 'stage_trainpct'), ('Matched', 'stage_matched')]
H_MULTS = [5.0, 7.0, 10.0]
H_PRIMARY = 7.0
K_FIXED = 0.7  # held fixed across all three h values -- NOT linked to h
RNG = np.random.RandomState(0)
N_BOOT = 1000
N_BOOT_ENGINE = 10000
_DF_CACHE = {}


def load_df():
    if 'df' not in _DF_CACHE:
        _DF_CACHE['df'] = pd.read_csv(DATA / 'per_sample_final_v4.csv', comment='#')
    return _DF_CACHE['df']


def get_md5():
    return (DATA / 'per_sample_final_v4.md5').read_text().strip()


def tex_header(func_name):
    return [f'% Generated by aggregate.py::{func_name}',
            f'% Source: data/per_sample_final_v4.csv, md5={get_md5()}']


def ecr_per_engine(sub, covered_col, isinf_col=None):
    if isinf_col is not None:
        sub = sub[~sub[isinf_col]]
    if len(sub) == 0:
        return np.nan
    return float(sub.groupby(['seed', 'unit'])[covered_col].mean().mean())


def worst_stage(vals):
    valid = {k: v for k, v in vals.items() if not np.isnan(v)}
    return min(valid, key=valid.get) if valid else None


def table_main():
    """Main table, finite-only ECR (Mondrian's headline number), unbounded
    rate as its own column."""
    df = load_df()
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for conv_name, stage_col in CONVENTIONS:
            for suffix, method_name in METHODS:
                covered_col = f'covered_{suffix}'
                isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    if len(s) == 0:
                        continue
                    ecr = ecr_per_engine(s, covered_col, isinf_col)
                    rate = float(s[isinf_col].mean()) if isinf_col else 0.0
                    n_inf = int(s[isinf_col].sum()) if isinf_col else 0
                    rows.append(dict(fd=fd, convention=conv_name, method=method_name, stage=stage,
                                      ecr_finite_only=ecr, unbounded_rate=rate,
                                      n_inf=n_inf, n_total=len(s)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'table_main_v4.csv', index=False)

    lines = tex_header('table_main') + [
        r'\begin{table}[t]',
        r'\caption{Main table (v4): 4 staging conventions $\times$ 4 methods $\times$ 3 stages, '
        r'per-engine ECR, h=7 primary. ECR is finite-only for all methods (unbounded intervals '
        r'excluded before the per-engine average -- see table\_mondrian\_unbounded\_v4 for the '
        r'two-convention comparison); unbounded rate given separately.}',
        r'\label{tab:main-v4}', r'\centering', r'\small',
        r'\begin{tabular}{lllccc}', r'\toprule',
        r'FD & Convention & Method & Stage & ECR (finite) & Unbounded rate \\', r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["convention"]} & {r["method"]} & {r["stage"].capitalize()} & '
                      f'{r["ecr_finite_only"]:.4f} & {r["n_inf"]}/{r["n_total"]} ({r["unbounded_rate"]:.4f}) \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_main_v4.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_main_v4.csv/.tex', out.shape)
    return out


def mondrian_unbounded_table():
    """Kept: the two-convention (unbounded-as-covered vs finite-only) comparison,
    now its own table rather than folded into table_main."""
    df = load_df()
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for conv_name, stage_col in CONVENTIONS:
            for suffix, method_name in [('mo', 'Mondrian CP (online)'), ('mf', 'Mondrian CP (split)')]:
                covered_col, isinf_col = f'covered_{suffix}', f'is_inf_{suffix}'
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    if len(s) == 0:
                        continue
                    covered_unb = s[covered_col] | s[isinf_col]
                    ecr_unb = float(covered_unb.groupby([s['seed'], s['unit']]).mean().mean())
                    ecr_fin = ecr_per_engine(s, covered_col, isinf_col)
                    rows.append(dict(fd=fd, convention=conv_name, method=method_name, stage=stage,
                                      ecr_unbounded_as_covered=ecr_unb, ecr_finite_only=ecr_fin,
                                      unbounded_rate=float(s[isinf_col].mean()),
                                      n_inf=int(s[isinf_col].sum()), n_total=len(s)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'table_mondrian_unbounded_v4.csv', index=False)
    print('wrote table_mondrian_unbounded_v4.csv', out.shape)
    return out


def compute_cohort_instances(df, stage_col):
    """(fd,seed,unit) instances with >=1 window in all 3 stages under stage_col.
    MUST group by fd too: unit ids are NOT globally unique (FD001 and FD003
    both have units 1..100), so a (seed,unit) tuple collides across FDs --
    grouping by (seed,unit) alone silently merges two different physical
    engines' stage sets. (Caught and fixed after the initial v2 pass reported
    221 total instances globally; the correct per-FD total is 455.)"""
    pivot = df.groupby(['fd', 'seed', 'unit'])[stage_col].apply(lambda s: set(pd.unique(s)))
    mask = pivot.apply(lambda s: {'early', 'middle', 'late'}.issubset(s))
    return set(pivot[mask].index)


def trainpct_and_cusum_cohort():
    df = load_df()
    trainpct_cohort = compute_cohort_instances(df, 'stage_trainpct')
    cusum_cohort = compute_cohort_instances(df, 'stage_cusum')
    total_instances = df[['fd', 'seed', 'unit']].drop_duplicates().shape[0]
    print(f'trainpct cohort: {len(trainpct_cohort)} instances (of {total_instances} total)')
    print(f'cusum cohort: {len(cusum_cohort)} instances (of {total_instances} total)')

    idx = pd.MultiIndex.from_tuples(list(trainpct_cohort), names=['fd', 'seed', 'unit'])
    df_idx = df.set_index(['fd', 'seed', 'unit'])
    df_trainpct_cohort = df_idx.loc[df_idx.index.isin(idx)].reset_index()

    idx2 = pd.MultiIndex.from_tuples(list(cusum_cohort), names=['fd', 'seed', 'unit'])
    df_cusum_cohort = df_idx.loc[df_idx.index.isin(idx2)].reset_index()

    def worst_table(df_in, stage_col, label, cohort_size_by_fd):
        rows = []
        for fd in FDS:
            sub_fd = df_in[df_in['fd'] == fd]
            for suffix, method_name in METHODS:
                covered_col = f'covered_{suffix}'
                isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
                vals = {}
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    vals[stage] = ecr_per_engine(s, covered_col, isinf_col)
                w = worst_stage(vals)
                rows.append(dict(fd=fd, method=method_name, n_cohort_instances=cohort_size_by_fd.get(fd, 0),
                                  early=vals['early'], middle=vals['middle'], late=vals['late'], worst_stage=w))
        out = pd.DataFrame(rows)
        out.to_csv(TABLES / f'{label}.csv', index=False)
        print(f'wrote {label}.csv', out.shape)
        return out

    trainpct_cohort_size = df_trainpct_cohort[['fd', 'seed', 'unit']].drop_duplicates().groupby('fd').size().to_dict()
    cusum_cohort_size = df_cusum_cohort[['fd', 'seed', 'unit']].drop_duplicates().groupby('fd').size().to_dict()

    out_trainpct = worst_table(df_trainpct_cohort, 'stage_trainpct', 'table_trainpct_cohort_v4', trainpct_cohort_size)
    out_cusum = worst_table(df_cusum_cohort, 'stage_cusum', 'table_cusum_cohort_check_v4', cusum_cohort_size)

    lines = tex_header('trainpct_and_cusum_cohort') + [
        r'\begin{table}[t]',
        r'\caption{Train-set-percentile convention, COHORT restriction: only (seed,unit) instances '
        r'with $\geq 1$ window in all 3 stages. Compare against table\_B\_trainpct\_v4 (full '
        r'availability) for whether the worst-stage finding depends on this structural imbalance.}',
        r'\label{tab:trainpct-cohort-v4}', r'\centering', r'\small',
        r'\begin{tabular}{llcccccc}', r'\toprule',
        r'FD & Method & N cohort & Early & Middle & Late & Worst \\', r'\midrule']
    for _, r in out_trainpct.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["n_cohort_instances"]} & {r["early"]:.4f} & '
                      f'{r["middle"]:.4f} & {r["late"]:.4f} & {r["worst_stage"]} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_trainpct_cohort_v4.tex').write_text('\n'.join(lines) + '\n')

    return out_trainpct, out_cusum


def trainpct_full_vs_cohort():
    """Side-by-side comparison: full-availability (b_full_availability) vs.
    cohort (trainpct_and_cusum_cohort) train-set-percentile results. Must run
    AFTER both of those (reads their .csv outputs from TABLES)."""
    full = pd.read_csv(TABLES / 'table_B_trainpct_v4.csv')
    cohort = pd.read_csv(TABLES / 'table_trainpct_cohort_v4.csv')
    m = pd.merge(
        full[['fd', 'method', 'early', 'middle', 'late', 'worst_stage']].rename(
            columns={'early': 'full_early', 'middle': 'full_middle', 'late': 'full_late', 'worst_stage': 'full_worst'}),
        cohort[['fd', 'method', 'n_cohort_instances', 'early', 'middle', 'late', 'worst_stage']].rename(
            columns={'early': 'cohort_early', 'middle': 'cohort_middle', 'late': 'cohort_late', 'worst_stage': 'cohort_worst'}),
        on=['fd', 'method'])
    m.to_csv(TABLES / 'table_trainpct_full_vs_cohort_v4.csv', index=False)

    lines = tex_header('trainpct_full_vs_cohort') + [
        r'\begin{table}[t]',
        r'\caption{Train-set-percentile convention: full-availability (455 instances) vs. '
        r'cohort ((fd,seed,unit) instances with $\geq 1$ window in all 3 stages) side by side.}',
        r'\label{tab:trainpct-full-vs-cohort-v4}', r'\centering', r'\small',
        r'\begin{tabular}{llccccccc}', r'\toprule',
        r'FD & Method & N coh. & Full E & Full M & Full L & Coh. E & Coh. M & Coh. L & Worst(full/coh) \\',
        r'\midrule']
    for _, r in m.iterrows():
        lines.append(
            f'{r["fd"]} & {r["method"]} & {r["n_cohort_instances"]} & '
            f'{r["full_early"]:.4f} & {r["full_middle"]:.4f} & {r["full_late"]:.4f} & '
            f'{r["cohort_early"]:.4f} & {r["cohort_middle"]:.4f} & {r["cohort_late"]:.4f} & '
            f'{r["full_worst"]}/{r["cohort_worst"]} \\\\'
        )
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_trainpct_full_vs_cohort_v4.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_trainpct_full_vs_cohort_v4.csv/.tex', m.shape)
    return m


def b_full_availability():
    """Full-availability version of the train-set-percentile table (all
    instances, no cohort restriction) -- kept for side-by-side comparison
    with table_trainpct_cohort."""
    df = load_df()
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in METHODS:
            covered_col = f'covered_{suffix}'
            isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
            vals = {}
            for stage in ['early', 'middle', 'late']:
                s = sub_fd[sub_fd['stage_trainpct'] == stage]
                vals[stage] = ecr_per_engine(s, covered_col, isinf_col)
            rows.append(dict(fd=fd, method=method_name, early=vals['early'], middle=vals['middle'],
                              late=vals['late'], worst_stage=worst_stage(vals)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'table_B_trainpct_v4.csv', index=False)
    print('wrote table_B_trainpct_v4.csv', out.shape)
    return out


def cluster_bootstrap_engine_block(sub_fd, covered_col, stage_col, stage_a, stage_b, n_boot=N_BOOT_ENGINE, rng=None):
    """Primary CI: block = one raw unit id's ENTIRE set of (seed,unit)
    instances across all 5 seeds it appears in as an eval engine. A block is
    drawn (or not) as a whole."""
    if rng is None:
        rng = RNG
    g = sub_fd.groupby(['seed', 'unit', stage_col])[covered_col].mean().unstack()
    if stage_a not in g.columns or stage_b not in g.columns:
        return dict(mean_diff=np.nan, ci_lo=np.nan, ci_hi=np.nan, n_pairs=0, n_unique_engines=0)
    valid = g.dropna(subset=[stage_a, stage_b])
    if len(valid) == 0:
        return dict(mean_diff=np.nan, ci_lo=np.nan, ci_hi=np.nan, n_pairs=0, n_unique_engines=0)
    diffs = (valid[stage_a] - valid[stage_b]).reset_index(name='diff')
    unit_to_diffs = diffs.groupby('unit')['diff'].apply(lambda x: x.values).to_dict()
    unique_units = np.array(list(unit_to_diffs.keys()))
    n_units = len(unique_units)
    boot_means = np.empty(n_boot)
    for b in range(n_boot):
        samp = rng.choice(unique_units, size=n_units, replace=True)
        vals = np.concatenate([unit_to_diffs[u] for u in samp])
        boot_means[b] = vals.mean()
    return dict(mean_diff=float(diffs['diff'].mean()),
                ci_lo=float(np.percentile(boot_means, 2.5)),
                ci_hi=float(np.percentile(boot_means, 97.5)),
                n_pairs=len(diffs), n_unique_engines=n_units)


def cluster_bootstrap_instance(sub_fd, covered_col, stage_col, stage_a, stage_b, n_boot=N_BOOT, rng=None):
    """Sensitivity column: old per-(seed,unit)-instance bootstrap (no
    cross-seed engine-identity pooling)."""
    if rng is None:
        rng = RNG
    g = sub_fd.groupby(['seed', 'unit', stage_col])[covered_col].mean().unstack()
    if stage_a not in g.columns or stage_b not in g.columns:
        return np.nan, np.nan
    valid = g.dropna(subset=[stage_a, stage_b])
    if len(valid) == 0:
        return np.nan, np.nan
    diffs = (valid[stage_a] - valid[stage_b]).values
    idx = np.arange(len(diffs))
    boot = [diffs[rng.choice(idx, size=len(idx), replace=True)].mean() for _ in range(n_boot)]
    return float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))


def paired_diff():
    df = load_df()
    methods = [('mc', 'MC-Dropout'), ('sp', 'Split CP')]
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in methods:
            covered_col = f'covered_{suffix}'
            for conv, stage_col, sa, sb, contrast in [
                ('Fixed-fraction', 'stage_fixed', 'middle', 'late', 'middle-late'),
                ('CUSUM', 'stage_cusum', 'late', 'middle', 'late-middle'),
            ]:
                blk = cluster_bootstrap_engine_block(sub_fd, covered_col, stage_col, sa, sb)
                ci_lo_inst, ci_hi_inst = cluster_bootstrap_instance(sub_fd, covered_col, stage_col, sa, sb)
                rows.append(dict(fd=fd, method=method_name, convention=conv, contrast=contrast,
                                  n_pairs=blk['n_pairs'], n_unique_engines=blk['n_unique_engines'],
                                  mean_diff=blk['mean_diff'],
                                  ci_lo_engine_block=blk['ci_lo'], ci_hi_engine_block=blk['ci_hi'],
                                  contains_zero_engine_block=(blk['ci_lo'] <= 0 <= blk['ci_hi']),
                                  ci_lo_instance=ci_lo_inst, ci_hi_instance=ci_hi_inst,
                                  contains_zero_instance=(ci_lo_inst <= 0 <= ci_hi_inst)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'paired_diff_v4.csv', index=False)

    lines = tex_header('paired_diff') + [
        r'\begin{table}[t]',
        r'\caption{Within-engine paired differences. Primary CI: unique-engine block bootstrap '
        r'(block = one raw unit id\'s full set of instances across all 5 seeds, 10{,}000 resamples, '
        r'drawn as a whole). Instance-level (old, per-(seed,unit), 1000 resamples) CI kept as a '
        r'sensitivity column.}',
        r'\label{tab:paired-diff-v4}', r'\centering', r'\small',
        r'\begin{tabular}{llllcc}', r'\toprule',
        r'FD & Method & Convention & Mean diff & 95\% CI (engine block) & 95\% CI (instance, sens.) \\',
        r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["convention"]} & {r["mean_diff"]:.4f} & '
                      f'[{r["ci_lo_engine_block"]:.4f}, {r["ci_hi_engine_block"]:.4f}] & '
                      f'[{r["ci_lo_instance"]:.4f}, {r["ci_hi_instance"]:.4f}] \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_paired_diff_v4.tex').write_text('\n'.join(lines) + '\n')
    print('wrote paired_diff_v4.csv/.tex', out.shape)
    print(f'contains_zero (engine block): {out["contains_zero_engine_block"].sum()}/16')
    return out


def matched_table():
    df = load_df()
    props = {}
    for fd in FDS:
        sub = df[df['fd'] == fd]
        p_early = (sub['stage_cusum'] == 'early').mean()
        p_middle = (sub['stage_cusum'] == 'middle').mean()
        p_late = (sub['stage_cusum'] == 'late').mean()
        props[fd] = (p_early, p_middle, p_late)

    rows_matched, rows_cusum = [], []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in METHODS:
            covered_col = f'covered_{suffix}'
            isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
            vals_m, vals_c = {}, {}
            for stage in ['early', 'middle', 'late']:
                sm = sub_fd[sub_fd['stage_matched'] == stage]
                sc = sub_fd[sub_fd['stage_cusum'] == stage]
                vals_m[stage] = ecr_per_engine(sm, covered_col, isinf_col)
                vals_c[stage] = ecr_per_engine(sc, covered_col, isinf_col)
            rows_matched.append(dict(fd=fd, method=method_name, **{f'matched_{k}': v for k, v in vals_m.items()},
                                      worst_stage=worst_stage(vals_m)))
            rows_cusum.append(dict(fd=fd, method=method_name, **{f'cusum_{k}': v for k, v in vals_c.items()}))
    out_m = pd.DataFrame(rows_matched).set_index(['fd', 'method'])
    out_c = pd.DataFrame(rows_cusum).set_index(['fd', 'method'])
    out = out_m.join(out_c).reset_index()
    diffs = []
    for stage in ['early', 'middle', 'late']:
        diffs.append((out[f'matched_{stage}'] - out[f'cusum_{stage}']).abs())
    max_abs_diff = float(pd.concat(diffs).max())
    out.to_csv(TABLES / 'table_matched_v4.csv', index=False)
    print(f'wrote table_matched_v4.csv, max |ECR_matched - ECR_cusum| across all cells = {max_abs_diff:.4f}')

    prop_lines = '; '.join(f'{fd}: early={p[0]:.4f}, middle={p[1]:.4f}, late={p[2]:.4f}' for fd, p in props.items())
    lines = tex_header('matched_table') + [
        r'\begin{table}[t]',
        r'\caption{Occupancy-matched pseudo-convention. Fixed chronological cut proportions are the '
        r'EVALUATION set\'s mean CUSUM(h=7) stage-occupancy proportions per FD (' + prop_lines.replace('_', r'\_') + r'). '
        rf'Max $|$ECR$_{{\rm matched}}$ - ECR$_{{\rm cusum}}|$ across all (fd,method,stage) cells = {max_abs_diff:.4f}.}}',
        r'\label{tab:matched-v4}', r'\centering', r'\small',
        r'\begin{tabular}{llcccc}', r'\toprule',
        r'FD & Method & Matched Early & Matched Middle & Matched Late & Worst \\', r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["matched_early"]:.4f} & {r["matched_middle"]:.4f} & '
                      f'{r["matched_late"]:.4f} & {r["worst_stage"]} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_matched_v4.tex').write_text('\n'.join(lines) + '\n')
    return out, max_abs_diff


def bucket_geometry():
    """Adds n_cohort_instances (trainpct cohort) to the per-(fd,seed) bucket
    geometry table."""
    df = load_df()
    thresh = pd.read_csv(DATA / 'trainpct_thresholds_final_v4.csv')
    trainpct_cohort = compute_cohort_instances(df, 'stage_trainpct')
    cohort_df = pd.DataFrame(list(trainpct_cohort), columns=['fd', 'seed', 'unit'])
    n_cohort = cohort_df.groupby(['fd', 'seed']).size().rename('n_cohort_instances').reset_index()
    out = thresh.merge(n_cohort, on=['fd', 'seed'], how='left')
    out['n_cohort_instances'] = out['n_cohort_instances'].fillna(0).astype(int)
    out.to_csv(TABLES / 'bucket_geometry_v4.csv', index=False)
    print('wrote bucket_geometry_v4.csv', out.shape)
    return out


def clocks():
    c = pd.read_csv(DATA / 'per_unit_clocks_final_v4.csv')
    rows = []
    for fd in FDS:
        sub = c[c['fd'] == fd]
        knee = sub['t_knee_norm'].dropna()
        cp = sub['t_cp_norm']
        rows.append(dict(fd=fd, n_units=len(sub), n_no_knee=sub['t_knee_norm'].isna().sum(),
                          n_cusum_not_triggered=(~sub['cusum_triggered']).sum(),
                          knee_mean=knee.mean(), knee_median=knee.median(),
                          cp_mean=cp.mean(), cp_median=cp.median(), one_minus_median_cp=1 - cp.median()))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A1_clocks_v4.csv', index=False)
    print('wrote A1_clocks_v4.csv', out.shape)
    return out


def a2_decile():
    df = load_df()
    df = df.copy()
    df['decile'] = np.minimum((df['t_norm'] * 10).astype(int), 9) + 1
    df['abs_err'] = (df['y_true'] - df['mu']).abs()
    rows = []
    for fd in FDS:
        sub = df[df['fd'] == fd]
        for dec in range(1, 11):
            d = sub[sub['decile'] == dec]
            if len(d) == 0:
                continue
            rows.append(dict(fd=fd, decile=dec, n=len(d),
                              failure_rate=1 - d['covered_sp'].mean(),
                              exceed_qhat_frac=(d['s_t'] > d['q_hat']).mean(),
                              median_s_t=d['s_t'].median(),
                              median_abs_err=d['abs_err'].median(),
                              median_sigma=d['sigma'].median()))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A2_decile_v4.csv', index=False)
    print('wrote A2_decile_v4.csv', out.shape)
    return out


def _h_suffix(h):
    return '' if h == H_PRIMARY else f'_h{int(h)}'


def table_h_sensitivity():
    """h-sensitivity table: k=K_FIXED held fixed across h in {5,7,10} (not
    linked to h), one row per (fd, method, h) -- 4 FD x 4 methods x 3 h = 48
    rows. MC-Dropout/Split CP's own interval bounds don't depend on h, but
    the CUSUM stage assignment they're binned into does (stage_cusum_h5/
    _h7(unsuffixed)/_h10 each partition samples differently), so their ECR
    still varies across h. Reintroduced in v3 against the corrected Mondrian
    CP (split) definition (see module docstring)."""
    df = load_df()
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in METHODS:
            for h in H_MULTS:
                sfx = _h_suffix(h)
                stage_col = f'stage_cusum{sfx}'
                covered_col = f'covered_{suffix}{sfx}' if suffix in ('mo', 'mf') else f'covered_{suffix}'
                isinf_col = f'is_inf_{suffix}{sfx}' if suffix in ('mo', 'mf') else None
                vals = {}
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    vals[stage] = ecr_per_engine(s, covered_col, isinf_col)
                w = worst_stage(vals)
                rows.append(dict(fd=fd, method=method_name, h_mult=h, k_mult=K_FIXED,
                                  early=vals['early'], middle=vals['middle'], late=vals['late'],
                                  worst_stage=w, late_is_worst=(w == 'late')))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'table_h_sensitivity_v4.csv', index=False)

    lines = tex_header('table_h_sensitivity') + [
        r'\begin{table}[t]',
        r'\caption{h-sensitivity (v3): CUSUM convention, k=0.7 held fixed across '
        r'h $\in \{5, 7, 10\}$ (not linked to h), finite-only ECR, per-engine, 4 FD '
        r'$\times$ 4 methods $\times$ 3 h values = 48 rows.}',
        r'\label{tab:h-sensitivity-v4}', r'\centering', r'\small',
        r'\begin{tabular}{llcccccc}', r'\toprule',
        r'FD & Method & h & k & Early & Middle & Late & Worst \\', r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["h_mult"]:.1f} & {r["k_mult"]:.1f} & '
                      f'{r["early"]:.4f} & {r["middle"]:.4f} & {r["late"]:.4f} & {r["worst_stage"]} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_h_sensitivity_v4.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_h_sensitivity_v4.csv/.tex', out.shape)
    return out


if __name__ == '__main__':
    table_main()
    mondrian_unbounded_table()
    b_full_availability()
    trainpct_and_cusum_cohort()
    trainpct_full_vs_cohort()
    paired_diff()
    matched_table()
    bucket_geometry()
    clocks()
    a2_decile()
    table_h_sensitivity()
