"""
Stage 0-R single aggregation entry point. Every table this file produces reads
ONLY from data/per_sample_final.csv (the canonical source built by
build_canonical.py) -- no table here re-derives Mondrian intervals, re-runs
CUSUM, or touches any file under legacy_leaked/ (v1's superseded per-sample
files, kept only as the discrepancy-diagnosis record -- see legacy_leaked/'s
note in the repo README).

Every .tex fragment's header comment records: the function in this file that
generated it, and the md5 of per_sample_final.csv at generation time (read
from data/per_sample_final.md5). All output is written to tables/.
"""
import numpy as np
import pandas as pd
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent  # scripts/ -> repo root
DATA = REPO / 'data'
TABLES = REPO / 'tables'
TABLES.mkdir(parents=True, exist_ok=True)
FDS = ['FD001', 'FD002', 'FD003', 'FD004']
METHODS = [('mc', 'MC-Dropout'), ('sp', 'Split CP'),
           ('mo', 'Mondrian CP (online)'), ('mf', 'Mondrian CP (frozen)')]
CONVENTIONS = [('Fixed-fraction', 'stage_fixed'), ('CUSUM', 'stage_cusum'),
               ('TrainPct', 'stage_trainpct'), ('Matched', 'stage_matched')]
H_MULTS = [5.0, 7.0, 10.0]
RNG = np.random.RandomState(0)
N_BOOT = 1000
_DF_CACHE = {}


def h_suffix(h):
    return '' if h == 7.0 else f'_h{int(h)}'


def load_df():
    if 'df' not in _DF_CACHE:
        _DF_CACHE['df'] = pd.read_csv(DATA / 'per_sample_final.csv', comment='#')
    return _DF_CACHE['df']


def get_md5():
    return (DATA / 'per_sample_final.md5').read_text().strip()


def tex_header(func_name):
    return [f'% Generated by aggregate.py::{func_name}',
            f'% Source: data/per_sample_final.csv, md5={get_md5()}']


def ecr_per_engine(sub, covered_col, isinf_col=None):
    if isinf_col is not None:
        sub = sub[~sub[isinf_col]]
    if len(sub) == 0:
        return np.nan
    return float(sub.groupby(['seed', 'unit'])[covered_col].mean().mean())


def cluster_bootstrap_engine(sub, covered_col, isinf_col=None, n_boot=N_BOOT):
    if isinf_col is not None:
        sub = sub[~sub[isinf_col]]
    if len(sub) == 0:
        return np.nan, np.nan
    g = sub.groupby(['seed', 'unit']).agg(nc=(covered_col, 'sum'), nt=(covered_col, 'size'))
    if len(g) == 0:
        return np.nan, np.nan
    idx = np.arange(len(g))
    nc, nt = g['nc'].values, g['nt'].values
    ecrs = []
    for _ in range(n_boot):
        samp = RNG.choice(idx, size=len(idx), replace=True)
        ecrs.append(nc[samp].sum() / nt[samp].sum())
    return float(np.percentile(ecrs, 2.5)), float(np.percentile(ecrs, 97.5))


def table_main():
    """Main table: 4 conventions x 4 methods x 3 stages, per-engine, h=7 (primary).
    Mondrian's 3 numbers: unbounded-as-covered / finite-only / unbounded-rate."""
    df = load_df()
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for conv_name, stage_col in CONVENTIONS:
            for suffix, method_name in METHODS:
                covered_col = f'covered_{suffix}'
                isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    if len(s) == 0:
                        continue
                    if isinf_col is not None:
                        covered_unb = s[covered_col] | s[isinf_col]
                        ecr_unb = float(covered_unb.groupby([s['seed'], s['unit']]).mean().mean())
                        ecr_fin = ecr_per_engine(s, covered_col, isinf_col)
                        rate = float(s[isinf_col].mean())
                        n_inf, n_total = int(s[isinf_col].sum()), len(s)
                        rows.append(dict(fd=fd, convention=conv_name, method=method_name, stage=stage,
                                          ecr_unbounded_as_covered=ecr_unb, ecr_finite_only=ecr_fin,
                                          unbounded_rate=rate, n_inf=n_inf, n_total=n_total))
                    else:
                        ecr = ecr_per_engine(s, covered_col)
                        rows.append(dict(fd=fd, convention=conv_name, method=method_name, stage=stage,
                                          ecr_unbounded_as_covered=np.nan, ecr_finite_only=ecr,
                                          unbounded_rate=0.0, n_inf=0, n_total=len(s)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'table_main_final.csv', index=False)

    lines = tex_header('table_main') + [
        r'\begin{table}[t]',
        r'\caption{Main table: 4 staging conventions $\times$ 4 methods $\times$ 3 stages, '
        r'per-engine ECR (h=7 primary). For Mondrian CP, three numbers: ECR treating unbounded '
        r'intervals as covered, ECR restricted to finite intervals, and the unbounded rate '
        r'(n\_inf/n\_total).}',
        r'\label{tab:main-final}', r'\centering', r'\small',
        r'\begin{tabular}{llllccc}', r'\toprule',
        r'FD & Convention & Method & Stage & ECR(unb=cov) & ECR(finite) & Unbounded rate \\',
        r'\midrule']
    for _, r in out.iterrows():
        unb = f'{r["ecr_unbounded_as_covered"]:.4f}' if not np.isnan(r['ecr_unbounded_as_covered']) else '--'
        lines.append(f'{r["fd"]} & {r["convention"]} & {r["method"]} & {r["stage"].capitalize()} & '
                      f'{unb} & {r["ecr_finite_only"]:.4f} & {r["n_inf"]}/{r["n_total"]} '
                      f'({r["unbounded_rate"]:.4f}) \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_main_final.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_main_final.csv/.tex', out.shape)
    return out


def h_sensitivity():
    """h-sensitivity, k=0.7 fixed throughout (this file's only CUSUM rule --
    the earlier 'k-linked' variant is NOT reproduced here; if wanted for an
    appendix it must come from a clearly-labeled separate rebuild, since
    per_sample_final.csv only carries k-fixed columns). 4 FD x 4 method x 3h
    = 48 cells, per-engine, no averaging across FD."""
    df = load_df()
    rows = []
    n_not_late_worst = 0
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in METHODS:
            covered_col = f'covered_{suffix}'
            isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
            for h in H_MULTS:
                sfx = h_suffix(h)
                stage_col = f'stage_cusum{sfx}'
                vals = {}
                for stage in ['early', 'middle', 'late']:
                    col = f'{covered_col}{sfx}' if suffix in ('mo', 'mf') else covered_col
                    isinf = f'{isinf_col}{sfx}' if isinf_col else None
                    s = sub_fd[sub_fd[stage_col] == stage]
                    vals[stage] = ecr_per_engine(s, col, isinf)
                valid = {k: v for k, v in vals.items() if not np.isnan(v)}
                worst = min(valid, key=valid.get) if valid else None
                is_not_late = worst is not None and worst != 'late'
                if is_not_late:
                    n_not_late_worst += 1
                rows.append(dict(fd=fd, method=method_name, h_mult=h, k_mult=0.7,
                                  early=vals['early'], middle=vals['middle'], late=vals['late'],
                                  worst_stage=worst, late_is_worst=(not is_not_late)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'h_sensitivity_kfixed_final.csv', index=False)
    print(f'wrote h_sensitivity_kfixed_final.csv: {len(out)} cells, {n_not_late_worst} NOT late-worst')

    lines = tex_header('h_sensitivity') + [
        r'\begin{table}[t]',
        r'\caption{h-sensitivity, k=0.7 fixed. 4 FD $\times$ 4 methods $\times$ 3 $h$ = 48 cells, '
        r'per-engine, no averaging across FD.}',
        r'\label{tab:hsens-final}', r'\centering', r'\small',
        r'\begin{tabular}{llcccc}', r'\toprule',
        r'FD & Method & $h$ & Early & Middle & Late & Worst \\', r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["h_mult"]:.0f} & {r["early"]:.4f} & '
                      f'{r["middle"]:.4f} & {r["late"]:.4f} & {r["worst_stage"]} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_h_sensitivity_final.tex').write_text('\n'.join(lines) + '\n')
    return out


def paired_diff():
    df = load_df()
    methods = [('mc', 'MC-Dropout'), ('sp', 'Split CP')]
    rows = []
    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        for suffix, method_name in methods:
            covered_col = f'covered_{suffix}'
            g = sub_fd.groupby(['seed', 'unit', 'stage_fixed'])[covered_col].mean().unstack()
            valid = g.dropna(subset=['middle', 'late'])
            diffs = (valid['middle'] - valid['late']).values
            idx = np.arange(len(diffs))
            boot = [diffs[RNG.choice(idx, size=len(idx), replace=True)].mean() for _ in range(N_BOOT)]
            lo, hi = np.percentile(boot, [2.5, 97.5])
            rows.append(dict(fd=fd, method=method_name, convention='Fixed-fraction',
                              contrast='middle-late', n_engines=len(diffs),
                              mean_diff=float(diffs.mean()), ci_lo=float(lo), ci_hi=float(hi)))

            g2 = sub_fd.groupby(['seed', 'unit', 'stage_cusum'])[covered_col].mean().unstack()
            valid2 = g2.dropna(subset=['middle', 'late'])
            diffs2 = (valid2['late'] - valid2['middle']).values
            idx2 = np.arange(len(diffs2))
            boot2 = [diffs2[RNG.choice(idx2, size=len(idx2), replace=True)].mean() for _ in range(N_BOOT)]
            lo2, hi2 = np.percentile(boot2, [2.5, 97.5])
            rows.append(dict(fd=fd, method=method_name, convention='CUSUM',
                              contrast='late-middle', n_engines=len(diffs2),
                              mean_diff=float(diffs2.mean()), ci_lo=float(lo2), ci_hi=float(hi2)))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'paired_diff_final.csv', index=False)

    lines = tex_header('paired_diff') + [
        r'\begin{table}[t]',
        r'\caption{Within-engine paired differences. Cluster bootstrap 95\% CI, clusters = '
        r'engine instances (1000 resamples).}',
        r'\label{tab:paired-diff-final}', r'\centering', r'\small',
        r'\begin{tabular}{llllcc}', r'\toprule',
        r'FD & Method & Convention & Contrast & Mean diff (n) & 95\% CI \\', r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["method"]} & {r["convention"]} & {r["contrast"]} & '
                      f'{r["mean_diff"]:.4f} (n={r["n_engines"]}) & [{r["ci_lo"]:.4f}, {r["ci_hi"]:.4f}] \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'table_paired_diff_final.tex').write_text('\n'.join(lines) + '\n')
    print('wrote paired_diff_final.csv/.tex', out.shape)
    return out


def a2_decile():
    df = load_df()
    df = df.copy()
    df['decile'] = np.minimum((df['t_norm'] * 10).astype(int), 9) + 1
    df['abs_err'] = (df['y_true'] - df['mu']).abs()
    rows = []
    for fd in FDS:
        sub = df[df['fd'] == fd]
        for dec in range(1, 11):
            d = sub[sub['decile'] == dec]
            if len(d) == 0:
                continue
            rows.append(dict(fd=fd, decile=dec, n=len(d),
                              failure_rate=1 - d['covered_sp'].mean(),
                              exceed_qhat_frac=(d['s_t'] > d['q_hat']).mean(),
                              median_s_t=d['s_t'].median(),
                              median_abs_err=d['abs_err'].median(),
                              median_sigma=d['sigma'].median()))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A2_decile_final.csv', index=False)
    lines = tex_header('a2_decile') + [
        r'\begin{table}[t]', r'\caption{A2: Split CP by t\_norm decile, by FD.}',
        r'\label{tab:A2-final}', r'\centering', r'\small',
        r'\begin{tabular}{lccccc}', r'\toprule',
        r'FD & Decile & Failure rate & Exceed $\hat q$ & Median $|s_t|$ & Median $|y-\mu|$ \\',
        r'\midrule']
    for _, r in out.iterrows():
        lines.append(f'{r["fd"]} & {r["decile"]} & {r["failure_rate"]:.4f} & '
                      f'{r["exceed_qhat_frac"]:.4f} & {r["median_s_t"]:.4f} & {r["median_abs_err"]:.4f} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    (TABLES / 'A2_decile_final.tex').write_text('\n'.join(lines) + '\n')
    print('wrote A2_decile_final.csv/.tex', out.shape)
    return out


def a3_crosstab():
    df = load_df()
    rows = []
    for fd in FDS:
        sub = df[df['fd'] == fd]
        ct = pd.crosstab(sub['stage_fixed'], sub['stage_cusum'], normalize='index')
        ct = ct.reindex(index=['early', 'middle', 'late'], columns=['early', 'middle', 'late'])
        for fixed_stage in ['early', 'middle', 'late']:
            for cusum_stage in ['early', 'middle', 'late']:
                rows.append(dict(fd=fd, fixed_stage=fixed_stage, cusum_stage=cusum_stage,
                                  proportion=ct.loc[fixed_stage, cusum_stage]))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A3_crosstab_final.csv', index=False)
    print('wrote A3_crosstab_final.csv', out.shape)
    return out


def a4_occupancy():
    df = load_df()
    rows = []
    for fd in FDS:
        sub = df[df['fd'] == fd]
        for convention, col in [('Fixed-fraction', 'stage_fixed'), ('CUSUM', 'stage_cusum'),
                                 ('TrainPct', 'stage_trainpct'), ('Matched', 'stage_matched')]:
            for stage in ['early', 'middle', 'late']:
                s = sub[sub[col] == stage]
                n_engines = s[['seed', 'unit']].drop_duplicates().shape[0]
                n_timepoints = len(s)
                prop = n_timepoints / len(sub) if len(sub) > 0 else np.nan
                rows.append(dict(fd=fd, convention=convention, stage=stage,
                                  n_engines=n_engines, n_timepoints=n_timepoints,
                                  timepoint_proportion=prop,
                                  mondrian_online_n_inf=int(s['is_inf_mo'].sum()),
                                  mondrian_online_denom=n_timepoints,
                                  mondrian_frozen_n_inf=int(s['is_inf_mf'].sum()),
                                  mondrian_frozen_denom=n_timepoints))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A4_occupancy_final.csv', index=False)
    print('wrote A4_occupancy_final.csv', out.shape)
    return out


def a1_clocks():
    clocks = pd.read_csv(DATA / 'per_unit_clocks_final.csv')
    rows = []
    for fd in FDS:
        sub = clocks[clocks['fd'] == fd]
        n_total = len(sub)
        n_no_knee = sub['t_knee_norm'].isna().sum()
        n_not_triggered = (~sub['cusum_triggered']).sum()
        knee = sub['t_knee_norm'].dropna()
        cp = sub['t_cp_norm']
        rows.append(dict(fd=fd, n_units=n_total, n_no_knee=n_no_knee,
                          n_cusum_not_triggered=n_not_triggered,
                          knee_mean=knee.mean(), knee_median=knee.median(),
                          cp_mean=cp.mean(), cp_median=cp.median(),
                          one_minus_median_cp=1 - cp.median()))
    out = pd.DataFrame(rows)
    out.to_csv(TABLES / 'A1_clocks_final.csv', index=False)
    print('wrote A1_clocks_final.csv', out.shape)
    return out


def b_and_c():
    df = load_df()
    for stage_col, label in [('stage_trainpct', 'B_trainpct_final'), ('stage_matched', 'C_matched_final')]:
        rows = []
        for fd in FDS:
            sub_fd = df[df['fd'] == fd]
            for suffix, method_name in METHODS:
                covered_col = f'covered_{suffix}'
                isinf_col = f'is_inf_{suffix}' if suffix in ('mo', 'mf') else None
                vals = {}
                for stage in ['early', 'middle', 'late']:
                    s = sub_fd[sub_fd[stage_col] == stage]
                    vals[stage] = ecr_per_engine(s, covered_col, isinf_col)
                valid = {k: v for k, v in vals.items() if not np.isnan(v)}
                worst = min(valid, key=valid.get) if valid else None
                rows.append(dict(fd=fd, method=method_name, early=vals['early'],
                                  middle=vals['middle'], late=vals['late'], worst_stage=worst))
        out = pd.DataFrame(rows)
        out.to_csv(TABLES / f'{label}.csv', index=False)
        print(f'wrote {label}.csv', out.shape)


if __name__ == '__main__':
    table_main()
    h_sensitivity()
    paired_diff()
    a1_clocks()
    a2_decile()
    a3_crosstab()
    a4_occupancy()
    b_and_c()
