"""
Aggregates results/forensics_2026-09-14_relabel/per_sample_relabeled.csv into:
  - table_main_relabeled.tex   : 4 FD x 2 conventions x 3 methods x 3 stages, ECR mean+-std
                                  over 5 seeds, + Mondrian CP inf-rate column
  - table_tests_relabeled.tex  : per-seed binomial p's (a), one-sample t-test (b), unit-level
                                  cluster bootstrap 95% CI (c) -- replaces the old pooled-p table
  - table_h_sensitivity_v2.tex : h in {5,7,10} sensitivity, all 3 methods
  - appendix_official_test.tex : the ORIGINAL item1 fixed-convention numbers on the OFFICIAL
                                  held-out test set (reused as-is from forensics_2026-09-11,
                                  no rerun), with the "early bucket structurally empty" note.
One-line answer: does the reversal survive on identical samples?
"""
import pandas as pd
import numpy as np
from pathlib import Path
from scipy.stats import binomtest, ttest_1samp

SOURCE_REPO = Path.home() / '论文4' / 'github_repo' / 'macp_rul'
IN = SOURCE_REPO / 'results' / 'forensics_2026-09-14_relabel' / 'per_sample_relabeled.csv'
OUT = Path(__file__).resolve().parents[2] / 'results' / 'forensics_2026-09-14_relabel'
NOTE_TABLES = Path.home() / '论文4' / 'note_qrei' / 'tables'
FDS = ['FD001', 'FD002', 'FD003', 'FD004']
METHODS = ['MC-Dropout', 'Split CP', 'Mondrian CP']
RNG = np.random.RandomState(0)
N_BOOT = 1000


def load():
    df = pd.read_csv(IN)
    return df


def cell_ecr_excl_inf(sub):
    """sub: rows for one (fd,seed,method,h,stage[,convention]) cell. Returns (ecr, n, n_inf)."""
    finite = sub[~sub['is_inf']]
    n_inf = int(sub['is_inf'].sum())
    n = len(finite)
    if n == 0:
        return np.nan, 0, n_inf
    return float(finite['covered'].mean()), n, n_inf


def per_unit_ecr_excl_inf(sub):
    """sub: rows for one (fd,seed,method,h,stage) cell, one row per (unit,t). Returns a
    DataFrame with one row per (seed,unit): n_covered, n_total (inf excluded)."""
    finite = sub[~sub['is_inf']]
    g = finite.groupby(['seed', 'unit']).agg(n_covered=('covered', 'sum'), n_total=('covered', 'size'))
    return g.reset_index()


def cluster_bootstrap_ci(unit_df, n_boot=N_BOOT, rng=RNG):
    """unit_df: columns seed,unit,n_covered,n_total (one row per cluster=unit-instance).
    Resample clusters with replacement, pool covered/total, compute ECR, repeat n_boot times."""
    if len(unit_df) == 0:
        return np.nan, np.nan
    idx = np.arange(len(unit_df))
    ecrs = []
    for _ in range(n_boot):
        samp = rng.choice(idx, size=len(idx), replace=True)
        nc = unit_df['n_covered'].values[samp].sum()
        nt = unit_df['n_total'].values[samp].sum()
        if nt > 0:
            ecrs.append(nc / nt)
    ecrs = np.array(ecrs)
    return float(np.percentile(ecrs, 2.5)), float(np.percentile(ecrs, 97.5))


def table_main(df):
    lines = []
    lines.append(r'% Table: same-sample stage-conditional ECR under two staging conventions.')
    lines.append(r'% Generated by analyze_relabeled.py::table_main from')
    lines.append(r'%   results/forensics_2026-09-14_relabel/per_sample_relabeled.csv')
    lines.append(r'% (produced by relabel_same_sample.py, macp_rul commit ec78ea8 at launch)')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\caption{Stage-conditional ECR (mean $\pm$ std over 5 seeds, inf-width '
                 r'samples excluded before averaging) on IDENTICAL held-out samples under '
                 r'two staging conventions applied to the same per-sample predictions. '
                 r'Mondrian CP additionally reports the fraction of samples that degenerated '
                 r'to an infinite-width interval (inf rate), which MC-Dropout and Split CP '
                 r'never exhibit (0\% in every cell).}')
    lines.append(r'\label{tab:main-relabeled}')
    lines.append(r'\centering')
    lines.append(r'\small')
    lines.append(r'\begin{tabular}{llcccc}')
    lines.append(r'\toprule')
    lines.append(r'Dataset & Convention & Method & Stage & ECR (mean $\pm$ std) & Inf rate \\')
    lines.append(r'\midrule')

    for fd in FDS:
        sub_fd = df[df['fd'] == fd]
        # Every row carries an h_mult tag even though stage_fixed doesn't depend on it;
        # filtering to h_mult==7.0 selects each sample exactly once, for either convention.
        hsel = sub_fd[sub_fd['h_mult'] == 7.0]
        for convention, stage_col in [('Fixed-fraction', 'stage_fixed'), ('CUSUM', 'stage_cusum')]:
            for method in METHODS:
                m_sub = hsel[hsel['method'] == method]
                for stage in ['early', 'middle', 'late']:
                    st_sub = m_sub[m_sub[stage_col] == stage]
                    if len(st_sub) == 0:
                        continue
                    per_seed = st_sub.groupby('seed').apply(cell_ecr_excl_inf_series)
                    ecr_mean = per_seed['ecr'].mean()
                    ecr_std = per_seed['ecr'].std()
                    inf_rate = st_sub['is_inf'].mean()
                    inf_str = f'{inf_rate*100:.1f}\\%' if method == 'Mondrian CP' else '0.0\\%'
                    lines.append(f'{fd} & {convention} & {method} & {stage.capitalize()} & '
                                 f'{ecr_mean:.3f} $\\pm$ {ecr_std:.3f} & {inf_str} \\\\')
            lines.append(r'\cmidrule{2-6}')
        lines[-1] = r'\midrule'

    lines[-1] = r'\bottomrule'
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')
    (OUT / 'table_main_relabeled.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_main_relabeled.tex')


def cell_ecr_excl_inf_series(sub):
    ecr, n, n_inf = cell_ecr_excl_inf(sub)
    return pd.Series({'ecr': ecr, 'n': n, 'n_inf': n_inf})


def table_tests(df):
    lines = []
    lines.append(r'% Table: per-cell statistical tests replacing the old pooled-p approach.')
    lines.append(r'% (a) 5 per-seed one-sided binomial p-values (H0: ECR>=0.90);')
    lines.append(r'% (b) one-sample t-test (n=5 seed means) against 0.90;')
    lines.append(r'% (c) unit-level cluster bootstrap 95% CI (1000 resamples, clusters =')
    lines.append(r'%     (seed,unit) instances pooled across all 5 seeds).')
    lines.append(r'% Generated by analyze_relabeled.py::table_tests.')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\caption{Per-cell significance tests against the $\mathrm{ECR}\geq 0.90$ '
                 r'target, same samples as Table~\ref{tab:main-relabeled} (Split CP shown; '
                 r'the pattern is materially the same for MC-Dropout and Mondrian CP, see '
                 r'main text). Binomial $p$-values are one-sided per seed '
                 r'($H_0:\mathrm{ECR}\geq 0.90$); the $t$-test is two-sided on the 5 seed '
                 r'means; the bootstrap CI pools all held-out units across seeds as clusters.}')
    lines.append(r'\label{tab:tests-relabeled}')
    lines.append(r'\centering')
    lines.append(r'\small')
    lines.append(r'\begin{tabular}{llcccc}')
    lines.append(r'\toprule')
    lines.append(r'Dataset & Convention & Stage & Binomial $p$ (5 seeds) & $t$-test $p$ (n=5) & '
                 r'Bootstrap 95\% CI \\')
    lines.append(r'\midrule')

    for fd in FDS:
        sub_fd = df[(df['fd'] == fd) & (df['method'] == 'Split CP') & (df['h_mult'] == 7.0)]
        for convention, stage_col in [('Fixed-fraction', 'stage_fixed'), ('CUSUM', 'stage_cusum')]:
            for stage in ['early', 'middle', 'late']:
                st_sub = sub_fd[sub_fd[stage_col] == stage]
                if len(st_sub) == 0:
                    continue
                per_seed = st_sub.groupby('seed').apply(cell_ecr_excl_inf_series).reset_index()
                pvals = []
                for _, r in per_seed.iterrows():
                    if r['n'] == 0:
                        continue
                    p = binomtest(int(round(r['ecr'] * r['n'])), int(r['n']), 0.90, alternative='less').pvalue
                    pvals.append(p)
                pval_str = '/'.join(f'{p:.3f}' for p in pvals)
                seed_means = per_seed['ecr'].dropna().values
                if len(seed_means) > 1 and seed_means.std() > 0:
                    t_p = ttest_1samp(seed_means, 0.90).pvalue
                    t_str = f'{t_p:.4f}'
                else:
                    t_str = 'n/a'
                unit_df = per_unit_ecr_excl_inf(st_sub)
                lo, hi = cluster_bootstrap_ci(unit_df)
                lines.append(f'{fd} & {convention} & {stage.capitalize()} & [{pval_str}] & '
                             f'{t_str} & [{lo:.3f}, {hi:.3f}] \\\\')

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')
    (OUT / 'table_tests_relabeled.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_tests_relabeled.tex')


def table_h_sensitivity(df):
    lines = []
    lines.append(r'% Table: h in {5,7,10} sigma0 sensitivity, all 3 methods, CUSUM convention,')
    lines.append(r'% same samples as table_main_relabeled.tex.')
    lines.append(r'% Generated by analyze_relabeled.py::table_h_sensitivity.')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\caption{Stage-conditional ECR sensitivity to the CUSUM threshold $h$, all '
                 r'three methods, on the same held-out samples as Table~\ref{tab:main-relabeled}. '
                 r'Mean $\pm$ std over 4 datasets $\times$ 5 seeds; inf-width samples excluded.}')
    lines.append(r'\label{tab:hsens-relabeled}')
    lines.append(r'\centering')
    lines.append(r'\begin{tabular}{llccc}')
    lines.append(r'\toprule')
    lines.append(r'Method & Stage & $h=5\sigma_0$ & $h=7\sigma_0$ & $h=10\sigma_0$ \\')
    lines.append(r'\midrule')

    for method in METHODS:
        for stage in ['early', 'middle', 'late']:
            row = [method, stage.capitalize()]
            for h in [5.0, 7.0, 10.0]:
                sub = df[(df['method'] == method) & (df['h_mult'] == h) & (df['stage_cusum'] == stage)]
                cellmeans = sub.groupby(['fd', 'seed']).apply(cell_ecr_excl_inf_series)['ecr']
                row.append(f'{cellmeans.mean():.3f} $\\pm$ {cellmeans.std():.3f}')
            lines.append(' & '.join(row) + r' \\')

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')
    (OUT / 'table_h_sensitivity_v2.tex').write_text('\n'.join(lines) + '\n')
    print('wrote table_h_sensitivity_v2.tex')


def appendix_official_test():
    """Reuses forensics_2026-09-11/item1_standard_cp_multiseed.csv AS-IS -- no rerun. This is
    the fixed-fraction convention evaluated on the OFFICIAL held-out test set (one point per
    unit, shared per-FD AVG_LIFETIME reference, clipped RUL), for comparison against the new
    same-sample analysis above."""
    item1 = pd.read_csv(SOURCE_REPO / 'results/forensics_2026-09-11/item1_standard_cp_multiseed.csv')
    lines = []
    lines.append(r'% Appendix: ORIGINAL fixed-fraction results on the OFFICIAL held-out test set')
    lines.append(r'% (one point per unit), reused as-is from')
    lines.append(r'%   results/forensics_2026-09-11/item1_standard_cp_multiseed.csv -- NOT rerun.')
    lines.append(r'% Generated by analyze_relabeled.py::appendix_official_test.')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\caption{For reference: Split CP stage-conditional ECR on the official '
                 r'C-MAPSS held-out test set (one truncation point per unit), the fixed-fraction '
                 r'convention as originally evaluated. \textbf{The early stage bucket is empty '
                 r'for every subset and every seed}: the official test protocol truncates every '
                 r'unit close to end-of-life, and combined with the standard 125-cycle RUL clip, '
                 r"no unit's normalized lifetime position $t_{\mathrm{norm}}$ can fall below the "
                 r'0.33 early/middle threshold under the shared per-subset lifetime reference '
                 r'used here. This is a structural property of the official benchmark protocol, '
                 r'not an artifact of our pipeline, and is why the main same-sample analysis '
                 r'(Table~\ref{tab:main-relabeled}) instead uses full held-out trajectories with '
                 r'a per-unit lifetime reference, which populates all three stages.}')
    lines.append(r'\label{tab:official-test}')
    lines.append(r'\centering')
    lines.append(r'\begin{tabular}{lcc}')
    lines.append(r'\toprule')
    lines.append(r'Dataset & Stage & ECR (mean $\pm$ std over 5 seeds) \\')
    lines.append(r'\midrule')
    for fd in FDS:
        for stage in ['middle', 'late']:
            sub = item1[(item1['fd'] == fd) & (item1['stage'] == stage)]
            if len(sub) == 0:
                continue
            lines.append(f'{fd} & {stage.capitalize()} & {sub["ecr"].mean():.3f} $\\pm$ '
                         f'{sub["ecr"].std():.3f} \\\\')
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')
    (OUT / 'appendix_official_test.tex').write_text('\n'.join(lines) + '\n')
    print('wrote appendix_official_test.tex')


def one_line_answer(df):
    """Does the reversal survive on identical samples?"""
    sub = df[(df['method'] == 'Split CP') & (df['h_mult'] == 7.0)]
    results = {}
    for convention, stage_col in [('fixed', 'stage_fixed'), ('cusum', 'stage_cusum')]:
        per_fd_worst = {}
        for fd in FDS:
            fd_sub = sub[sub['fd'] == fd]
            stage_ecr = {}
            for stage in ['early', 'middle', 'late']:
                st_sub = fd_sub[fd_sub[stage_col] == stage]
                if len(st_sub) == 0:
                    continue
                ecr, n, n_inf = cell_ecr_excl_inf(st_sub)
                stage_ecr[stage] = ecr
            if stage_ecr:
                per_fd_worst[fd] = min(stage_ecr, key=stage_ecr.get)
        results[convention] = per_fd_worst
    print('\nWorst stage per FD, fixed convention:', results['fixed'])
    print('Worst stage per FD, CUSUM convention:', results['cusum'])
    flips = sum(1 for fd in FDS if results['fixed'].get(fd) != results['cusum'].get(fd))
    answer = (f"On identical held-out samples (same predictions, same intervals), the "
              f"worst-covered stage differs between the fixed-fraction and CUSUM staging "
              f"conventions for {flips}/4 datasets -- the reversal "
              f"{'SURVIVES' if flips >= 3 else ('PARTIALLY SURVIVES' if flips >= 1 else 'DOES NOT SURVIVE')} "
              f"the same-sample correction.")
    print('\nONE-LINE ANSWER:', answer)
    (OUT / 'one_line_answer.txt').write_text(answer + '\n')
    return answer


if __name__ == '__main__':
    df = load()
    table_main(df)
    table_tests(df)
    table_h_sensitivity(df)
    appendix_official_test()
    one_line_answer(df)
